### ISSUE TITLE
앞으로 남은 일들

### ISSUE THREAD

**Issue by ygeenee616** [ProjectInTheClass/OAOmates#7]
-  데이터를 <수정하기>에서 입력받은 후 서버에 올리도록 하기
- 서버에 올라간 데이터를 뷰에서 확인 할 수 있도록 하기
- 어떤 데이터가 서버에 올라가야 하는지 정리하기
- 매칭 요청을 눌렀을 때 사용자가 매칭완료되서 삭제됨(-)
- 찜 버튼을 눌렀을 때 찜 화면에서 확인이 가능하도록 하기(-)
- 추천하기 프로그램 완성하기 (추천율 계산, 추천도 막대바에서 추천율 보이도록 하기)

<UI에서 남은 작업들>
- MyView의 스크롤 문제

**Comment by kyeongseo90** [comment]
스크롤 문제 해결
